x-common-config:
  &common-config
  network_mode: host
  ipc: host
  restart: unless-stopped

x-cpu-config:
  &cpu-config
  env_file: .env.cpu

x-gpu-config:
  &gpu-config
  runtime: nvidia
  env_file: .env.gpu

services:

  ros2router:
    image: husarnet/ros2router:1.6.3
    <<: *common-config
    environment:
      - USER
      # ==========================
      # envs for Husarnet setup
      # ==========================
      - ROS_DISCOVERY_SERVER=${ROBOT_NAMESPACE}:11811
      - DISCOVERY_SERVER_ID=10 # need to be different as ros2router on ROSbot
      # ==========================
      # envs for LAN setup
      # ==========================
      # - ROS_LOCALHOST_ONLY=0
      # - HUSARNET_PARTICIPANT_ENABLED=false

  rviz:
    image: husarion/rviz2:iron-12.4.5-20240104
    <<: 
      - *common-config
      - *cpu-config
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./config/rosbot.rviz:/default.rviz
    environment:
      - FASTRTPS_DEFAULT_PROFILES_FILE=/shm-only.xml
      - USER
    command: rviz2 -d /default.rviz