x-common-config:
  &common-config
  network_mode: host
  ipc: host
  environment:
    - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp

services:

  rosbot:
    image: husarion/rosbot:humble-0.11.0-20231211
    <<: *common-config
    devices:
      - ${SERIAL_PORT:?err}
    command: >
      ros2 launch rosbot_bringup combined.launch.py
        mecanum:=${MECANUM:-False}
        serial_port:=$SERIAL_PORT
        serial_baudrate:=576000

  rplidar:
    image: husarion/rplidar:humble-1.0.1-20231219
    <<: *common-config
    devices:
      - /dev/ttyRPLIDAR:/dev/ttyUSB0
    command: ros2 launch sllidar_ros2 sllidar_launch.py serial_baudrate:=${LIDAR_BAUDRATE:-115200}

  navigation:
    image: husarion/navigation2:humble-1.1.12-20231219
    <<: *common-config
    depends_on:
      rplidar: { condition: service_healthy }
      rosbot: { condition: service_healthy }
    volumes:
      - ./config/nav2_${CONTROLLER:-rpp}_params.yaml:/params.yaml
      - ./maps:/maps
    environment:
      - SAVE_MAP_PERIOD=${SAVE_MAP_PERIOD}
    command: >
      ros2 launch nav2_bringup bringup_launch.py
        slam:=${SLAM:-True}
        params_file:=/params.yaml
        map:=/maps/map.yaml
        use_sim_time:=False
