x-common-config:
  &common-config
  network_mode: host
  ipc: host
  env_file: dds.env

services:

  rviz:
    image: husarion/rviz2:iron-12.4.5-20231122
    <<: *common-config
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./config/rosbot.rviz:/root/.rviz2/default.rviz
    # runtime: nvidia # uncomment if you want to use GPU
    environment:
      - DISPLAY=${DISPLAY:?err}
      - LIBGL_ALWAYS_SOFTWARE=1 # comment if you want to use GPU
      # - NVIDIA_VISIBLE_DEVICES=all # uncomment if you want to use GPU
      # - NVIDIA_DRIVER_CAPABILITIES=all # uncomment if you want to use GPU
      - ROS_DISCOVERY_SERVER=${ROSBOT_HOSTNAME}:11811
