x-net-config:
  &net-config
  network_mode: host
  ipc: host

x-gpu-config:
  &gpu-config
  runtime: nvidia
  environment:
    - DISPLAY=${DISPLAY:?err}
    - NVIDIA_VISIBLE_DEVICES=all
    - NVIDIA_DRIVER_CAPABILITIES=all
    - FASTRTPS_DEFAULT_PROFILES_FILE=/shm-only.xml

x-cpu-config:
  &cpu-config
  environment:
    - DISPLAY=${DISPLAY:?err}
    - LIBGL_ALWAYS_SOFTWARE=1
    - FASTRTPS_DEFAULT_PROFILES_FILE=/shm-only.xml

services:

  rviz:
    image: husarion/rviz2:iron-nightly
    network_mode: host
    ipc: host
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./config/rosbot.rviz:/root/.rviz2/default.rviz
    environment:
      - DISPLAY=${DISPLAY:?err}
      - LIBGL_ALWAYS_SOFTWARE=1
      - ROS_DISCOVERY_SERVER=rosbot2r:11811
      - FASTRTPS_DEFAULT_PROFILES_FILE=/shm-only.xml
