x-gpu-config:
  &gpu-config
  runtime: nvidia
  environment:
    - DISPLAY=${DISPLAY:?err}
    - NVIDIA_VISIBLE_DEVICES=all
    - NVIDIA_DRIVER_CAPABILITIES=all

services:

  rosbot:
    image: husarion/rosbot-gazebo:humble-0.10.3-20231127
    <<: *gpu-config
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    command: ros2 launch rosbot_gazebo simulation.launch.py mecanum:=${MECANUM:-True}

  navigation:
    image: husarion/navigation2:humble-1.1.12-20231219

    <<: *gpu-config
    volumes:
      - ./config/nav2_${CONTROLLER:-rpp}_params.yaml:/params.yaml
      - ./maps:/maps
    environment:
      - SAVE_MAP_PERIOD=${SAVE_MAP_PERIOD}
    command: >
      ros2 launch nav2_bringup bringup_launch.py
        slam:=${SLAM:-True}
        params_file:=/params.yaml
        map:=/maps/map.yaml
        use_sim_time:=True

  rviz:
    image: husarion/rviz2:humble-11.2.6-20230809
    <<: *gpu-config
    depends_on:
      rosbot: { condition: service_healthy }
      navigation: { condition: service_healthy }
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./config/rosbot.rviz:/root/.rviz2/default.rviz
