x-gpu-config:
  &gpu-config
  runtime: nvidia
  env_file: .env.gpu

services:

  rosbot:
    image: husarion/webots:humble-2023.0.4-20230809-stable
    <<: *gpu-config
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    command: ros2 launch webots_ros2_husarion rosbot_launch.py

  navigation:
    image: husarion/navigation2:humble-namespace
    <<: *gpu-config
    volumes:
      - ./config/nav2_${CONTROLLER:-rpp}_params.yaml:/params.yaml
      - ./maps:/maps
    environment:
      - SAVE_MAP_PERIOD=${SAVE_MAP_PERIOD}
    command: >
      ros2 launch /husarion_utils/bringup_launch.py
        slam:=${SLAM:-True}
        params_file:=/params.yaml
        map:=/maps/map.yaml
        use_sim_time:=True

  rviz:
    image: husarion/rviz2:humble-11.2.6-20230809
    <<: *gpu-config
    depends_on:
      navigation: { condition: service_healthy }
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./config/rosbot.rviz:/root/.rviz2/default.rviz
