x-gpu-config:
  &gpu-config
  runtime: nvidia
  env_file: .env.gpu

services:

  rosbot:
    image: husarion/rosbot-gazebo:humble-0.13.0-20240115
    <<: *gpu-config
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      - ROBOT_NAMESPACE=${ROBOT_NAMESPACE}
    command: >
      ros2 launch rosbot_gazebo simulation.launch.py
        mecanum:=${MECANUM:-True}
        namespace:=${ROBOT_NAMESPACE}

  navigation:
    image: husarion/navigation2:humble-namespace
    <<: *gpu-config
    volumes:
      - ./config/nav2_${CONTROLLER:-rpp}_params.yaml:/params.yaml
      - ./maps:/maps
    environment:
      - ROBOT_NAMESPACE=${ROBOT_NAMESPACE}
      - SAVE_MAP_PERIOD=${SAVE_MAP_PERIOD}
    command: >
      ros2 launch /husarion_utils/bringup_launch.py
        slam:=${SLAM:-True}
        params_file:=/params.yaml
        map:=/maps/map.yaml
        use_sim_time:=True

  foxglove:
    image: husarion/foxglove:1.84.0
    ports:
      - 8080:8080
      - 8765:8765
    volumes:
      - ./config/layout.json:/foxglove/default-layout.json
    environment:
      - ROBOT_NAMESPACE=${ROBOT_NAMESPACE}
      # - DS_TYPE=rosbridge-websocket
      # - DS_PORT=9090
      - DS_TYPE=foxglove-websocket
      - DS_PORT=8765
      - DS_HOST=foxglove-ds
      - UI_PORT=8080
      - DISABLE_CACHE=true
      - DISABLE_INTERACTION=false

  # rosbridge-ds:
  #   image: husarion/rosbridge-server:humble-1.3.1-20230831-stable
  #   ports:
  #     - 9090:9090
  #   command: ros2 launch rosbridge_server rosbridge_websocket_launch.xml

  foxglove-ds:
    image: husarion/foxglove-bridge:humble-0.7.3-20240108
    command: ros2 launch foxglove_bridge foxglove_bridge_launch.xml port:=8765 capabilities:=[clientPublish,connectionGraph,assets]
