services:

  ros2router:
    image: husarnet/ros2router:1.3.0
    network_mode: host
    volumes:
      - ./filter.yaml:/filter.yaml
    environment:
      - ROS_DISCOVERY_SERVER=rosbot2r:11811
      - DISCOVERY_SERVER_ID=10
      - IGNORE_PARTICIPANTS_FLAGS=filter_different_host

