x-gpu-config:
  &gpu-config
  runtime: nvidia
  env_file: .env.gpu

services:

  rosbot:
    image: husarion/rosbot-gazebo:humble-0.13.0-20240115
    <<: *gpu-config
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      - ROBOT_NAMESPACE=${ROBOT_NAMESPACE}
    command: >
      ros2 launch rosbot_gazebo simulation.launch.py
        mecanum:=${MECANUM:-True}
        namespace:=${ROBOT_NAMESPACE}

  navigation:
    image: husarion/navigation2:humble-1.1.12-20240123
    <<: *gpu-config
    volumes:
      - ./config/nav2_${CONTROLLER:-rpp}_params.yaml:/params.yaml
      - ./maps:/maps
    environment:
      - ROBOT_NAMESPACE=${ROBOT_NAMESPACE}
      - SAVE_MAP_PERIOD=${SAVE_MAP_PERIOD}
    command: >
      ros2 launch /husarion_utils/bringup_launch.py
        slam:=${SLAM:-True}
        params_file:=/params.yaml
        map:=/maps/map.yaml
        use_sim_time:=True

  rviz:
    image: husarion/rviz2:humble-11.2.6-20230809
    <<: *gpu-config
    depends_on:
      rosbot: { condition: service_healthy }
      navigation: { condition: service_healthy }
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./config/rosbot.rviz:/default.rviz
    command: >
      rviz2 -d /default.rviz --ros-args
        -r /tf:=tf
        -r /tf_static:=tf_static
        -r __ns:=/${ROBOT_NAMESPACE}
