x-common-config:
  &common-config
  network_mode: host
  ipc: host
  restart: unless-stopped

x-cpu-config:
  &cpu-config
  env_file: .env.cpu

x-gpu-config:
  &gpu-config
  runtime: nvidia
  env_file: .env.gpu

x-dds-envs:
  &dds-envs
  env_file: .env.dds

services:

  ros2router:
    image: husarnet/ros2router:1.8.0 #1.7.0 #1.6.3
    <<: *common-config
    volumes:
      - ./config.base.yaml:/config.base.yaml
      - ./router_config.yaml:/router_config.yaml
    #   - ./filter.yaml:/filter.yaml
    environment:
      - USER
      - ROBOT_NAMESPACE
      - PARTICIPANTS=shm,husarnet
      # ==========================
      # envs for Husarnet setup
      # ==========================
      # - ROS_DISCOVERY_SERVER=${ROBOT_NAMESPACE}:11811
      # - DISCOVERY_SERVER_ID=10 # need to be different as ros2router on ROSbot
      # ==========================
      # envs for LAN setup
      # ==========================
      # - ROS_LOCALHOST_ONLY=0
      # - HUSARNET_PARTICIPANT_ENABLED=false
    # command: ddsrouter -c /router_config.yaml

  rviz:
    image: husarion/rviz2:humble-11.2.9-20240111
    <<:
      - *common-config
      - *cpu-config
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./config/rosbot.rviz:/default.rviz
    environment:
      - FASTRTPS_DEFAULT_PROFILES_FILE=/shm-only.xml
      # - FASTRTPS_DEFAULT_PROFILES_FILE=/husarnet-fastdds.xml
      - USER=${USER:-root}
    command: >
      rviz2 -d /default.rviz --ros-args
        -r /tf:=tf
        -r /tf_static:=tf_static
        -r __ns:=/${ROBOT_NAMESPACE}
