---
amcl:
  ros__parameters:
    use_sim_time: false

    global_frame_id: map
    odom_frame_id: odom
    base_frame_id: base_link
    scan_topic: scan

    robot_model_type: nav2_amcl::DifferentialMotionModel

    set_initial_pose: true
    always_reset_initial_pose: true

    tf_broadcast: true
    transform_tolerance: 1.0

    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2

    # Beam skipping - ignores beams for which a majoirty of particles do not agree with the map
    # prevents correct particles from getting down weighted because of unexpected obstacles
    # such as humans
    do_beamskip: false
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.9
    beam_skip_threshold: 0.3

    lambda_short: 0.1
    laser_likelihood_max_dist: 2.0
    laser_max_range: 12.0
    laser_min_range: 0.2
    laser_model_type: likelihood_field
    max_beams: 60
    max_particles: 500
    min_particles: 200

    pf_err: 0.05
    pf_z: 0.99

    recovery_alpha_fast: 0.0
    recovery_alpha_slow: 0.0

    resample_interval: 1
    save_pose_rate: 0.5
    sigma_hit: 0.2

    update_min_a: 0.3
    update_min_d: 0.2

    z_hit: 0.5
    z_max: 0.05
    z_rand: 0.5
    z_short: 0.05

    initial_pose:
      x: 0.0
      y: 0.0
      yaw: 0.0

amcl_map_client:
  ros__parameters:
    use_sim_time: false

amcl_rclcpp_node:
  ros__parameters:
    use_sim_time: false


bt_navigator:
  ros__parameters:
    use_sim_time: false
    global_frame: map
    robot_base_frame: base_link
    odom_topic: odometry/filtered

    bt_loop_duration: 10
    default_server_timeout: 20
    wait_for_service_timeout: 1000
    action_server_result_timeout: 900.0
    navigators: [navigate_to_pose, navigate_through_poses]
    navigate_to_pose:
      plugin: nav2_bt_navigator/NavigateToPoseNavigator
    navigate_through_poses:
      plugin: nav2_bt_navigator/NavigateThroughPosesNavigator
    plugin_lib_names:
      - nav2_compute_path_to_pose_action_bt_node
      - nav2_follow_path_action_bt_node
      - nav2_back_up_action_bt_node
      - nav2_spin_action_bt_node
      - nav2_wait_action_bt_node
      - nav2_clear_costmap_service_bt_node
      - nav2_is_stuck_condition_bt_node
      - nav2_goal_reached_condition_bt_node
      - nav2_goal_updated_condition_bt_node
      - nav2_initial_pose_received_condition_bt_node
      - nav2_reinitialize_global_localization_service_bt_node
      - nav2_rate_controller_bt_node
      - nav2_distance_controller_bt_node
      - nav2_speed_controller_bt_node
      - nav2_truncate_path_action_bt_node
      - nav2_goal_updater_node_bt_node
      - nav2_recovery_node_bt_node
      - nav2_pipeline_sequence_bt_node
      - nav2_round_robin_node_bt_node
      - nav2_transform_available_condition_bt_node
      - nav2_time_expired_condition_bt_node
      - nav2_distance_traveled_condition_bt_node
      - nav2_remove_passed_goals_action_bt_node
      - nav2_compute_path_through_poses_action_bt_node

bt_navigator_rclcpp_node:
  ros__parameters:
    use_sim_time: false

controller_server:
  ros__parameters:
    use_sim_time: false

    controller_frequency: 5.0

    # if velocity is below threshold value it is set to 0
    min_x_velocity_threshold: 0.01    # Measured
    min_y_velocity_threshold: 0.01    # Measured
    min_theta_velocity_threshold: 0.1 # Measured

    progress_checker_plugin: progress_checker
    progress_checker:
      plugin: nav2_controller::SimpleProgressChecker
      required_movement_radius: 0.5
      movement_time_allowance: 10.0

    goal_checker_plugin: goal_checker
    goal_checker:
      plugin: nav2_controller::SimpleGoalChecker
      xy_goal_tolerance: 0.1
      yaw_goal_tolerance: 0.3
      stateful: true # if stateful is True goal checker will not check if the xy position matches again once it is found to be True.

    controller_plugins: [FollowPath]
    FollowPath:
      plugin: nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController

      # Velocity/acceleration limits also have to be adjusted in the velocity smoother
      desired_linear_vel: 0.4
      lookahead_dist: 0.5
      transform_tolerance: 0.25

      # Adaptive lookahead gain
      use_velocity_scaled_lookahead_dist: false # Currently doesn't work, uncomment in next release
      lookahead_time: 1.5
      min_lookahead_dist: 0.3
      max_lookahead_dist: 0.6

      # Approach to goal
      min_approach_linear_velocity: 0.2
      approach_velocity_scaling_dist: 0.5

      # Collision detector
      use_collision_detection: true
      max_allowed_time_to_collision_up_to_carrot: 1.0

      # Curvature velocity penalty
      use_regulated_linear_velocity_scaling: true
      regulated_linear_scaling_min_radius: 0.5

      # Cost spaces velocity penalty
      use_cost_regulated_linear_velocity_scaling: true # Whether to use the regulated features for proximity to obstacles (e.g. slow in close proximity to obstacles).
      cost_scaling_dist: 0.55
      cost_scaling_gain: 0.8 # Should be <= 1.0
      inflation_cost_scaling_factor: 3.0

      # Minimum speed in high cost spaces with high curvature
      regulated_linear_scaling_min_speed: 0.25

      allow_reversing: false
      use_rotate_to_heading: true
      rotate_to_heading_min_angle: 0.7

      # it is only used when rotating to heading (use_rotate_to_heading)
      # for some reason rotate_to_heading_angular_vel is ignored and robot rotates with
      # max_angular_accel/10. angular velocity (that's why it is set to higher value)
      max_angular_accel: 7.0
      rotate_to_heading_angular_vel: 2.5
      use_interpolation: true

controller_server_rclcpp_node:
  ros__parameters:
    use_sim_time: false

local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: false

      global_frame: odom
      robot_base_frame: base_link

      update_frequency: 3.0
      publish_frequency: 2.0

      width: 4
      height: 4
      resolution: 0.04

      always_send_full_costmap: true
      rolling_window: true

      footprint: '[[0.10, 0.12], [0.10, -0.12], [-0.10, -0.12], [-0.10, 0.12]]'

      plugins: [static_layer, obstacle_layer, inflation_layer]
      static_layer:
        plugin: nav2_costmap_2d::StaticLayer
        enabled: true
        map_subscribe_transient_local: true
      obstacle_layer:
        plugin: nav2_costmap_2d::ObstacleLayer
        enabled: true
        observation_sources: scan
        scan:
          topic: scan
          max_obstacle_height: 2.0
          clearing: true
          marking: true
          data_type: LaserScan
          raytrace_max_range: 3.0
          raytrace_min_range: 0.0
          obstacle_max_range: 2.5
          obstacle_min_range: 0.0
      inflation_layer:
        plugin: nav2_costmap_2d::InflationLayer
        enabled: true
        cost_scaling_factor: 3.0
        inflation_radius: 0.55

  local_costmap_client:
    ros__parameters:
      use_sim_time: false
  local_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: false

global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: false

      global_frame: map
      robot_base_frame: base_link

      update_frequency: 1.0
      publish_frequency: 1.0

      resolution: 0.05

      always_send_full_costmap: true
      track_unknown_space: true # if False, treats unknown space as free space, else as unknown space

      footprint: '[[0.10, 0.12], [0.10, -0.12], [-0.10, -0.12], [-0.10, 0.12]]'

      plugins: [static_layer, obstacle_layer, inflation_layer]
      static_layer:
        plugin: nav2_costmap_2d::StaticLayer
        enabled: true
        map_subscribe_transient_local: true
      obstacle_layer:
        plugin: nav2_costmap_2d::ObstacleLayer
        enabled: true
        observation_sources: scan
        scan:
          topic: scan
          max_obstacle_height: 2.0
          clearing: true
          marking: true
          data_type: LaserScan
          raytrace_max_range: 3.0
          raytrace_min_range: 0.0
          obstacle_max_range: 2.5
          obstacle_min_range: 0.0
      inflation_layer:
        plugin: nav2_costmap_2d::InflationLayer
        enabled: true
        cost_scaling_factor: 3.0
        inflation_radius: 0.55

  global_costmap_client:
    ros__parameters:
      use_sim_time: false
  global_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: false

map_server:
  ros__parameters:
    use_sim_time: false
    yaml_filename: map.yaml

map_saver:
  ros__parameters:
    use_sim_time: false
    save_map_timeout: 5.0
    free_thresh_default: 0.25
    occupied_thresh_default: 0.65
    map_subscribe_transient_local: true

planner_server:
  ros__parameters:
    use_sim_time: false
    expected_planner_frequency: 1.0

    planner_plugins: [GridBased]
    GridBased:
      plugin: nav2_smac_planner/SmacPlanner2D
      tolerance: 0.125 # tolerance for planning if unable to reach exact pose, in meters
      downsample_costmap: false # whether or not to downsample the map
      downsampling_factor: 1 # multiplier for the resolution of the costmap layer (e.g. 2 on a 5cm costmap would be 10cm)
      allow_unknown: true # allow traveling in unknown space
      max_iterations: 500000 # maximum total iterations to search for before failing (in case unreachable), set to -1 to disable
      max_on_approach_iterations: 500 # maximum number of iterations to attempt to reach goal once in tolerance
      max_planning_time: 3.0 # max time in s for planner to plan, smooth
      cost_travel_multiplier: 2.5 # Cost multiplier to apply to search to steer away from high cost areas. Larger values will place in the center of aisles more exactly (if non-`FREE` cost potential field exists) but take slightly longer to compute. To optimize for speed, a value of 1.0 is reasonable. A reasonable tradeoff value is 2.0. A value of 0.0 effective disables steering away from obstacles and acts like a naive binary search A*.
      use_final_approach_orientation: false # Whether to set the final path pose at the goal's orientation to the requested orientation (false) or in line with the approach angle so the robot doesn't rotate to heading (true)
      smoother:
        max_iterations: 500
        w_smooth: 0.3
        w_data: 0.2
        tolerance: 1.0e-6

planner_server_rclcpp_node:
  ros__parameters:
    use_sim_time: false

<robot_namespace>/slam_toolbox:
  ros__parameters:

    # Plugin params
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: None

    # ROS Parameters
    odom_frame: odom
    map_frame: map
    base_frame: base_link
    scan_topic: scan
    use_map_saver: true
    mode: mapping #localization

    # lifelong params
    lifelong_search_use_tree: false
    lifelong_minimum_score: 0.1
    lifelong_iou_match: 0.85
    lifelong_node_removal_score: 0.04
    lifelong_overlap_score_scale: 0.06
    lifelong_constraint_multiplier: 0.08
    lifelong_nearby_penalty: 0.001
    lifelong_candidates_scale: 0.03

    debug_logging: false
    throttle_scans: 1
    transform_publish_period: 0.04
    map_update_interval: 2.0
    resolution: 0.05
    max_laser_range: 12.0 #for rastering images
    minimum_time_interval: 0.5
    transform_timeout: 0.2
    tf_buffer_duration: 10.
    stack_size_to_use: 40000000 #// program needs a larger stack size to serialize large maps

    # General Parameters
    use_scan_matching: true
    use_scan_barycenter: true
    minimum_travel_distance: 0.3
    minimum_travel_heading: 0.4
    scan_buffer_size: 10
    scan_buffer_maximum_scan_distance: 10.0
    link_match_minimum_response_fine: 0.1
    link_scan_maximum_distance: 1.5
    loop_search_maximum_distance: 3.0
    do_loop_closing: true
    loop_match_minimum_chain_size: 10
    loop_match_maximum_variance_coarse: 3.0
    loop_match_minimum_response_coarse: 0.35
    loop_match_minimum_response_fine: 0.45

    # Correlation Parameters - Correlation Parameters
    correlation_search_space_dimension: 0.5
    correlation_search_space_resolution: 0.01
    correlation_search_space_smear_deviation: 0.1

    # Correlation Parameters - Loop Closure Parameters
    loop_search_space_dimension: 8.0
    loop_search_space_resolution: 0.05
    loop_search_space_smear_deviation: 0.03

    # Scan Matcher Parameters
    distance_variance_penalty: 0.5
    angle_variance_penalty: 1.0

    fine_search_angle_offset: 0.00349
    coarse_search_angle_offset: 0.349
    coarse_angle_resolution: 0.0349
    minimum_angle_penalty: 0.9
    minimum_distance_penalty: 0.5
    use_response_expansion: true

behavior_server:
  ros__parameters:
    use_sim_time: false

    global_frame: odom
    robot_base_frame: base_link
    transform_tolerance: 0.25

    costmap_topic: local_costmap/costmap_raw
    footprint_topic: local_costmap/published_footprint
    cycle_frequency: 5.0

    behavior_plugins: [spin, backup, drive_on_heading, assisted_teleop, wait]
    spin:
      plugin: nav2_behaviors/Spin
    backup:
      plugin: nav2_behaviors/BackUp
    drive_on_heading:
      plugin: nav2_behaviors/DriveOnHeading
    wait:
      plugin: nav2_behaviors/Wait
    assisted_teleop:
      plugin: nav2_behaviors/AssistedTeleop

    # spin & backup
    simulate_ahead_time: 0.5

    # spin
    max_rotational_vel: 0.6
    min_rotational_vel: 0.4
    rotational_acc_lim: 3.2

waypoint_follower:
  ros__parameters:
    use_sim_time: false
    loop_rate: 5
    stop_on_failure: false
    waypoint_task_executor_plugin: wait_at_waypoint
    wait_at_waypoint:
      plugin: nav2_waypoint_follower::WaitAtWaypoint
      enabled: true
      waypoint_pause_duration: 200

smoother_server:
  ros__parameters:
    use_sim_time: false

velocity_smoother:
  ros__parameters:
    use_sim_time: false

    smoothing_frequency: 5.0
    scale_velocities: false
    feedback: OPEN_LOOP
    max_velocity: [0.5, 0.0, 1.5]   # Measured: MAX[1.0, 0.0, 3.14] (decreased for safety)
    min_velocity: [-0.5, 0.0, -1.5] # Measured: MAX[1.0, 0.0, 3.14] (decreased for safety)
    max_accel: [1.0, 0.0, 3.2]
    max_decel: [-1.0, 0.0, -3.2]  # Measured
    # used in the CLOSED_LOOP feedback mode
    # odom_topic: "odometry/filtered"
    odom_duration: 0.1
    deadband_velocity: [0.01, 0.01, 0.1] # Measured
    velocity_timeout: 1.0
