x-common-config:
  &common-config
  network_mode: host
  ipc: host
  env_file:
    - .env

x-gpu-config:
  &gpu-config
  runtime: nvidia
  environment:
    - DISPLAY=${DISPLAY:?err}
    - NVIDIA_VISIBLE_DEVICES=all
    - NVIDIA_DRIVER_CAPABILITIES=all

x-cpu-config:
  &cpu-config
  environment:
    - DISPLAY=${DISPLAY:?err}
    - LIBGL_ALWAYS_SOFTWARE=1

services:

  rosbot_gazebo:
    image: husarion/rosbot-gazebo:${ROS_DISTRO}-0.16.1-20250901
    <<: [*gpu-config, *common-config]
    volumes:
      - ./dds-config-udp.xml:/udp_profile.xml:ro
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    command: >
      ros2 launch rosbot_gazebo simulation.launch.py
        robot_model:=${ROBOT_MODEL:-err}
        rviz:=False

  rosbot_navigation:
    image: husarion/rosbot-autonomy:${ROS_DISTRO}-0.1.0-20250916
    <<: [*common-config]
    volumes:
      - ./config/nav2_params.yaml:/nav2_params.yaml
      - ./dds-config-udp.xml:/udp_profile.xml:ro
      - ./maps:/maps
    command: >
      ros2 launch rosbot_navigation bringup.launch.py
        controller:=${CONTROLLER:-mppi}
        map:=/maps/map.yaml
        robot_model:=${ROBOT_MODEL:-err}
        params_file:=/nav2_params.yaml
        slam:=${SLAM:-True}
        use_sim_time:=True
